/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spreadtrum_opencvtestfr_FaceDetection */

#ifndef _Included_com_spreadtrum_opencvtestfr_FaceDetection
#define _Included_com_spreadtrum_opencvtestfr_FaceDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spreadtrum_opencvtestfr_FaceDetection
 * Method:    faceRec
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_spreadtrum_opencvtestfr_FaceDetection_faceRec
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
